name: Vercel CLI Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Puxar Variáveis de Ambiente e Enviar para Vercel
        run: |
          rm -rf .git
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}